apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-project-deployment
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-project
  template:
    metadata:
      labels:
        app: k8s-project
    spec:
      containers:
        - name: k8s-project-container
          image: aq496/k8s-project:v1.0
          ports:
            - containerPort: 8000   # Change if your app uses another port
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-project-service
  namespace: production
spec:
  type: NodePort
  selector:
    app: k8s-project
  ports:
    - port: 8000       # service port
      targetPort: 8000 # same as containerPort
      nodePort: 30080  # NodePort (30000–32767)